vim.g.netrw_bufsettings = 'noma nomod nu rnu nobl nowrap ro'
vim.g.editorconfig = true
vim.g.autoformat = true
vim.opt.guicursor = ""
vim.opt.cursorline = true
vim.opt.colorcolumn = "0"
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.laststatus = 3
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.backspace = "indent,eol,start"
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.smartcase = true
vim.opt.ignorecase = true
vim.opt.mouse = a
vim.opt.termguicolors = true
vim.opt.lazyredraw = true
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.opt.signcolumn = "yes"
vim.opt.isfname:append("@-@")
vim.opt.updatetime = 50
vim.opt.autoread = true
vim.opt.wrap = false
vim.opt.wildmode = "longest,list"
vim.opt.swapfile = false
