import = ["~/.config/alacritty/themes/themes/dracula_plus.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 19

[shell]
program = "/bin/zsh"
